import type { AcceptanceObligation, ArtifactState, VerificationDebt, VerificationEvidence, WorkspaceState } from './types.js';
export declare function artifactState(workspace: WorkspaceState, path: string): ArtifactState;
export declare function mutateArtifact(workspace: WorkspaceState, path: string, sequence: number): ArtifactState;
export declare function observeArtifact(workspace: WorkspaceState, path: string, sequence: number): ArtifactState;
export declare function artifactRevisionSnapshot(workspace: WorkspaceState): Record<string, number>;
export declare function createVerificationDebtForArtifact(workspace: WorkspaceState, path: string, sequence: number): VerificationDebt;
export declare function createWorkspaceMutationDebt(workspace: WorkspaceState, sequence: number): VerificationDebt;
export declare function debtSatisfied(workspace: WorkspaceState, debt: VerificationDebt): boolean;
export declare function openVerificationDebts(workspace: WorkspaceState): VerificationDebt[];
export declare function pruneVerificationDebts(workspace: WorkspaceState): void;
export declare function applyReadback(workspace: WorkspaceState, path: string): number;
export declare function applyVerificationEvidence(workspace: WorkspaceState, evidence: VerificationEvidence): number;
export declare function openAcceptance(obligations: Iterable<AcceptanceObligation>): AcceptanceObligation[];
export declare function satisfyAcceptance(obligation: AcceptanceObligation, evidence: string, selfAttested?: boolean): void;
export declare function waiveAcceptance(obligation: AcceptanceObligation, reason: string): void;
export declare function updateAcceptanceAfterMutation(obligations: Iterable<AcceptanceObligation>, path: string, evidence: string): string[];
export declare function updateAcceptanceAfterObservation(obligations: Iterable<AcceptanceObligation>, path: string | undefined, relevant: boolean, evidence: string): string[];
export declare function setArtifactDependencies(workspace: WorkspaceState, path: string, dependencies: Iterable<string>): void;
export declare function dependentClosure(workspace: WorkspaceState, path: string, maxDepth?: number): string[];
export declare function createDependentVerificationDebts(workspace: WorkspaceState, mutatedPath: string, sequence: number): VerificationDebt[];
